### ISSUE TITLE
Difficult to tap attackers / Can't attack when over empty chip block

### ISSUE THREAD

**Issue by vertigo220** [ochadenas/cpudefense#104]
As the title says, if attackers are going through an empty block, they can't be tapped. This makes scenarios where they are on the wire for a short length before going through a block, then more short wire before reaching another block, and so on (e.g. level 22) difficult to tap them in time.

Edited to change 21 to 22

**Comment by ochadenas** [comment]
Hmmm ... you're right, if you tap on a slot, then the buy-chip-menu has priority. Which means that attackers effectively can't be inverted when on a slot.

However, I don't know how to mend this. In fact, this used to be the other way round in early versions, and that was even more annoying: It was impossible to buy chips when an attacker was on the slot.

**Comment by ochadenas** [comment]
Sure that you mean level 21 and not 22? 

Because, in level 22 the lanes are quite short indeed. Perhaps they should be made somewhat longer.

**Comment by vertigo220** [comment]
> Sure that you mean level 21 and not 22?
> 
> Because, in level 22 the lanes are quite short indeed. Perhaps they should be made somewhat longer.

You're right, level 22. I've found it's hard to know what level I'm on and I've made that mistake on a few issues then caught it and changed it. It would be really helpful to have it show the level number while playing.

**Comment by vertigo220** [comment]
> Hmmm ... you're right, if you tap on a slot, then the buy-chip-menu has priority. Which means that attackers effectively can't be inverted when on a slot.
> 
> However, I don't know how to mend this. In fact, this used to be the other way round in early versions, and that was even more annoying: It was impossible to buy chips when an attacker was on the slot.

Yeah, I think I saw that, and I agree, I'm not sure of a good solution. It could use logic like if the box contains a number that would be made smaller by inverting it, invert it, and if it doesn't contain a number or it contains one that would be made larger by inverting it, select the box. But then that could be used to "cheat" and tap numbers inside boxes to auto-invert them only when they'd be decreased. Another option would be to increase the zone around boxes on the sides outside the traces, so tapping above/below/beside them would activate them, and tapping inside them would activate them only when empty, otherwise it would flip any attackers inside them. Still another possibility would be that if they contain an attacker, it would show a popup giving a choice to flip the attacker on the opposite side from the build/upgrade options. That would require another click, but that probably wouldn't be too bad.

**Comment by Cwpute** [comment]
> increase the zone around boxes on the sides outside the traces

I'm not sure this is ideal, since some levels can get pretty cramped already, but why not, with some testing this could do.

> Still another possibility would be that if they contain an attacker, it would show a popup […]. That would require another click, but that probably wouldn't be too bad.

That could work if attackers weren't constantly moving :/ in earlier levels, or with heavy slowed down attackers thanks to recruits, this is a good idea… but in the rush of later levels this is just impossible to handle. Not mentioning the horrendous mistakes you could make, selling your SHR6 chip when you wanted to invert an attacker !

My suggestion would be to have longer wires in-selected areas between chip slots, so that you get more time to tap on attackers between them (whether they are empty or full). As a rule of thumb, a level should then probably contain at least one long wire to confortably tap on the attackers (like level 8 does, since it was modified to allow this).
Then it could even be used as a difficulty slider while procedurally making endless mode levels 😉 #95

**Comment by ochadenas** [comment]
I'd like to close this. I think that the rule "buy/sell menu has priority over tapping attackers" is ok most of the time. Any logic behind (trying to be smart) will confuse the player, and there will always be situations in which the decision is felt to be wrong.

Level 22 has a longer entry line now. And what's more, because it comes quite late in the game now, it should be feasible with all the heroes you've got by then. I've just managed to finish it on turbo without loss of life using a combination of ACC, SUB 6, and CLK 4. Plus the Cernettes at level 8, but I have not even upgraded Dorothy Vaughan, so there is still some margin.
