### ISSUE TITLE
zero defense circuits in random levels in endless mode

### ISSUE THREAD

**Issue by Khaledsame** [ochadenas/cpudefense#111]
Hey, I love you game, but there is a weird bug in level 5 Endless mode!
[Screenshot_20240228-013909_ChipDefense.png](https://github.com/ochadenas/cpudefense/assets/94556591/0c0fd3c5-cdda-4792-b0a6-40ca482d9e5a)

There is no defence there and they are always attacking.

**Comment by CrsiX** [comment]
I want to add that this is _not_ specific to level 5 (they were generated). It happened to me in level 33 of the endless mode just now as you can see above the CPU on the left. It is impossible to play this level since there are no chip slots between the CPU and the the spawn:

![bug-endless-33](https://github.com/ochadenas/cpudefense/assets/47722349/385f36e5-3edd-4919-8871-fcdc23f9d9fa)

**Comment by CrsiX** [comment]
I suggest to check in the generator that there is *at least* one chip slot between the spawn and the CPU. I have already won rounds were I only had one slot, so this is possible. I would recommend at least two slots, though.

**Comment by Khaledsame** [comment]
Yes, i hope they fix it soon.

**Comment by Khaledsame** [comment]
Ok, I got you, it's all generated randomly.
Thank you.

**Comment by CrsiX** [comment]
Please do not close this issue. It is still an issue that should be tracked and resolved at some point. Just because it is randomly generated doesn't mean that this should happen.

Also, could you rename this issue to something like "zero defense circuits in random levels in endless mode" or similar? It is not specific to level 5. Thank you :)

**Comment by Khaledsame** [comment]
OK.

**Comment by ochadenas** [comment]
I admit that the random level generation still needs some work. And that situations like this should be avoided. Will try to come up with some kind of solution to this ...

In the meantime, if you are stuck, you can go to "Settings" and uncheck "Keep levels in endless mode". This will generate a new one each time you restart the level.

**Comment by CrsiX** [comment]
> In the meantime, if you are stuck, you can go to "Settings" and uncheck "Keep levels in endless mode". This will generate a new one each time you restart the level.

Thanks for the tip. I re-played the last seven levels because I thought it may change things, but it did not, before I found that switch ;)

**Comment by ochadenas** [comment]
added some code in 1.30 to guarantee that there are at least 2 nodes on each track.
