### ISSUE TITLE
Bug: selling MEM chips (v1.33)

### ISSUE THREAD

**Issue by Kutabu** [ochadenas/cpudefense#141]
Selling MEM chips happens instantly in version 1.33. Game does not wait for the cooldown time to end.

And this is combined with:
All currently saved attackers are destroyed, if there is more than one in memory (after upgrades of the MEM chip).

**Comment by Kutabu** [comment]
I thought about it: The very very long time to wait for a full clearance makes it impractical to sell da chip. Often new attackers may come an occupie a slot in the chip.

Maybe it can be a feature, that it is possible to sell a MEM chip with all attackers in memory. But you only receive money for the free memory-slots.
Because you have to tab the MEM anyway, there must be at least one free slot after the initial cooldown, that triggers the selling activity.

**Comment by ochadenas** [comment]
The current behaviour (1.36) is: It is always possible to sell a MEM chip even with numbers inside *except* when it has a thick frame. During that time, tapping on the chip will first clear the last occupied slot. I think this is sufficiently practical.

The other thing is that the attackers inside are not released. This turns out to be a bit tricky. But there is issue #120 for this, so I'm closing this one.
