### ISSUE TITLE
Mem level beyond 4. V1.34

### ISSUE THREAD

**Issue by Mortis03** [ochadenas/cpudefense#152]
I have maxed out all heros on endless but can't figure out how to get mem chip past 4 slots.  I assume each level is a slot.  After I upgrade to level 4, only option available is to sell. Is this a bug or am I not doing something correctly?

Thanks

**Comment by ochadenas** [comment]
This is intentional. Currently, MEM chips are limited to 4 slots.

There has been a lot of discussions here whether MEM chips are overpowered or too weak (or both). The 4-slots-limit is an attempt to balance game play. Maybe we'll have to change this in future, but for now I'd rather leave it as it is.

**Comment by Mortis03** [comment]
Ah OK thank you for explaining.  Why does the hero go level 7?

**Comment by ochadenas** [comment]
That's a bug. In fact, as you mention it, Leibniz was affected by Sid Meier, which shouldn't be the case. Changed in 1.35.

**Comment by Mortis03** [comment]
Ahh.  Makes sense.  Thanks for the info!
