### ISSUE TITLE
Game crashes loading first level. Unplayable

### ISSUE THREAD

**Issue by mruncreative** [ochadenas/cpudefense#168]
LineageOS 21 Android 14
Loading the first level I get to see some story text for a sec and then the game is back to the main menu. Somtimes a crash message appears. I think the app crashed and restartet.

**Comment by ochadenas** [comment]
Hi, which version is this? Are you playing for the first time?

Might be a memory issue. Could you try the "Disable background" option (under "settings")?

**Comment by mruncreative** [comment]
Newest version on F-Droid. Yes, first time. My phone has 6 GB RAM and works just fine.

**Comment by ochadenas** [comment]
Was able to reproduce the bug. This is probably due to the new font introduced in 1.37. If the "ubuntu mono" font is not available on the device, the game crashes as soon as it tries to write something using this typeface. I thought that the font files would get bundled with the release, but this seems not to be the case.

Added a fallback in 1.40. If the font is not available, the system's standard monospace font is used, whatever that is.

PS, you can see the game's version on top of the INFO screen.

**Comment by mruncreative** [comment]
Update 1.39 didnt help

**Comment by ochadenas** [comment]
Version 1.40 is on F-Droid now, so if you have some time I'd be glad to know whether the problem is fixed for your device. Thanks!

**Comment by mruncreative** [comment]
1.40 fixed the issue. It's now playable.
