### ISSUE TITLE
Please make it so SHR doesn't attack attackers that are already 0

### ISSUE THREAD

**Issue by sere3925sere** [ochadenas/cpudefense#170]
Would make the game slightly less reliant on random chance. Sometimes you have a big number floating towards SHR, and 0 just slightly ahead of it, and this results in SHR going all out on 0 and not touching the big guy.

Played version 1.39.

**Comment by ochadenas** [comment]
Some time ago, the chips behaviour was changed already. In current versions SHR targets the largest number, if there are more than one possibilities.

Of course, this doesn't prevent a situation where a 0 enters the chip's range just before the big one. Then it will fire at the first attacker it encounters and enter into cool down phase. 

This particular situation can easily be avoided. I mean, I can change the game so that SHR does not have effect on 0 numbers _at all_. I only hope that this doesn't cause confusion on lower levels, so that seemingly chips don't work at all.

Generally the chips are not *that* intelligent, I mean, they don't think "better leave this one alone, because the chip behind me will take care of that, and just wait half a second for the big guy to enter my range". They are in fact quite stupid.

PS. Thanks for stating your version number in the issue ;)

**Comment by ochadenas** [comment]
changed in version 1.41
