### ISSUE TITLE
Upgrade numbers on chips are cut off

### ISSUE THREAD

**Issue by mruncreative** [ochadenas/cpudefense#175]
For example instead of SUB 3 You'll see SUB followed by three dots from the three ends of the 3.
Maybe use a thinner space or drop the space if it's monospace.

**Comment by ochadenas** [comment]
This is probably a consequence of the fix of issue #168. For some reason, your device can't display the font used in the game, even though it _should_ be available on standard Android systems. Since version 1.40, in this case the "standard system monospace font" is used, whatever this is. If it is a bit larger than expected, the last letter will be cut off.

Maybe I could add a kind of correction code for these cases, so that the font size is reduced accordingly.

**Comment by ochadenas** [comment]
Version 1.49: The text on the chips is scaled down if it is too big to fit into the rectangle.
