### ISSUE TITLE
[1.40] Jack Kilby "Unwanted Chip Count" doesn't affect number of unwanted chips

### ISSUE THREAD

**Issue by torbium** [ochadenas/cpudefense#176]
I feel like Jack Kilby is not doing anything at the moment. E.g. on endless 15, when I have -0 unwanted chips, there are 4 unwanted chips on the board. When I upgrade him to -2, or -7, there are still 4 unwanted chips. This is also the case for other levels.

**Comment by ochadenas** [comment]
There is no fixed 1:1 correspondence between unwanted chips and Kilby's level. In fact, there is no _longer_ such a correspondence; there used to be, but it has changed some versions ago, because players asked for a fairer level generator. The downside is that the number of chips is not completely predictable.

An explanation for your observation may be that the "difficulty" of unwanted chips is taken into account. For example, a NOP counts 0.5 difficulty points, DUP counts 2.0. And furthermore, also the level layout plays a role. Levels with short paths from entry to CPU are considered harder, and they do add to the global difficulty.

The "target difficulty" for level 16 is 10.0, lowered by a certain compensation for short paths. Each level of Kilby further reduces this target by 1.0 - for example, you could have a target of 4.2. Unwanted chips are randomly chosen to fill up this difficulty, but you don't know whether there will be four NOP chips, or one DUP, or one SHL and two ADD. Furthermore, because only certain values are possible, sometimes a chip can't be placed.

So think of Kilby's effect more of an *average* difficulty reduction.

**Comment by torbium** [comment]
I think I kinda get it now. It would be nice if the game somehow told you what this hero really does, but on the other hand I also don't know how to briefly describe the effect of him. I mean you don't want to have an entire paragraph there, when all the other heroes are described by a short sentence.

**Comment by ochadenas** [comment]
Added a "Did you know" text with an explanation of Kilby's effect.
