### ISSUE TITLE
Needs an option to not immediately send the first wave

### ISSUE THREAD

**Issue by Ryder17z** [ochadenas/cpudefense#180]
On a small screen, the game is kind of finicky feeling, making real-time management of towers less fun than intended.

**Comment by ochadenas** [comment]
What if you hit the "pause" button immediately after starting the level? Wouldn't that help?

**Comment by Ryder17z** [comment]
Other TD games I've played either do not send the first wave before you
click a button to do so or are generous with the a 30 second delay before
sending the first wave

**Comment by ochadenas** [comment]
I fear that introducing a 30-seconds-delay would generate a storm of unfriendly comments here. Better not try that.

The button would be feasible, but I don't really see the necessity. I really often use the pause button. Just to look around, get an idea of the level layout, and buy the first chips. Because since version 1.27, chips can be bought and sold in paused state.

The new button would only save one tap. On the other hand, on easier levels or if you don't want to think before the first wave, it would require one _more_ tap. So there is not much to be gained.

**Comment by Ryder17z** [comment]
If it's on by default yes, but I didn't specify it should be (my suggestion
would opt-in)

**Comment by ochadenas** [comment]
I'd like to close this issue. I think that this would only add complexity without any real benefit.

**Comment by Ryder17z** [comment]
I disagree with your assessment, but I respect your decision. Keep up the good work.

**Comment by Cwpute** [comment]
I second this suggestion. The wave would start paused, and the player would need to unpause.
Make this an option and each will be satisfied with their own preferences :)
