### ISSUE TITLE
"heroes" section does not appear everytime

### ISSUE THREAD

**Issue by vivienprouvot** [ochadenas/cpudefense#20]
Once I finish a level, the blue button labbeled "heroes" appears and I can hire some amazing bonuses.
But when I click on select level, and choose a level, this button dosnt appear so I can't change my hire actions.
Now that I finished the game, it is a problem when I want to test other heroes.

**Comment by ochadenas** [comment]
The button appears only if the player has coins to spend. Assuming that if you can't hire new heroes, there is no point in going to the heroes screen.

But you are right: this also makes it impossible to try another combination.

**Comment by ochadenas** [comment]
The blue button should always be displayed once the last level has been reached.

**Comment by vivienprouvot** [comment]
Thank you for your answers. This game is an excellent game and worth be known and improved.

**Comment by ochadenas** [comment]
Thank you! I will definitively continue to work on the game, but I have been very busy lately.

**Comment by juleskers** [comment]
Thank you for the enjoyable game!

Wouldn't it make sense to **always** have the heroes-button available, as soon as the player collected their first coin? 

'm currently stuck on level 8, and would like to "respec" my heroes tree to try a different strategy, but cannot, since I collected all possible coins already, so have no way to re-enter the screen.

**Comment by ochadenas** [comment]
You are probably right about displaying the buttons. Anyway,  I'll think of a different way to reset the heroes ...

If you are stuck, just play level 7 again and catch the running coin.

**Comment by juleskers** [comment]
I'll see if the bonus coin in level 7 can unstick me (that level currently says "3 of 2 coins collected 😛)

As for the heroes-button, however you decide to make it accessible, I've always learned that it's better UI to gray-out/disable buttons, rather than hide them completely.
That way the user at least knows they're looking in the right place, when they find the disabled button.

**Comment by juleskers** [comment]
P.s. In case the user-perspective might help you:
The first places I looked to re-enter the heroes screen was in the main menu (maybe an additional button had appeared?), then under "settings" (although that would have surprised me a little)

**Comment by ochadenas** [comment]
Some of the points mentioned in this issue have been dealt with:
- the hero button is available regardless of coins to spend
- there is a "replay" button within the level

It is still not possible to access the heroes screen from the main menu. I will keep that in mind for a possible future re-design.
