### ISSUE TITLE
Cryptocoin has no indication of life left

### ISSUE THREAD

**Issue by Itja** [ochadenas/cpudefense#33]
It is just rotating when hit with no indication if the Shift- or the Sub-Towers did anything until it finally reaches the end and draws a life. Really frustrating experience to not know how much life that thing had left.

**Comment by ochadenas** [comment]
These coins are meant to be a little challenge, so that the game won't be *too* easy. It is true that it is not possible to see their current value. But you know that
- the coins are about as strong as the strongest numbers in that wave
- they spin when hit
- and they are not affected by MEM and ACC.

So if a coin makes it through, give the level another try, with one more upgrade to your SUB and SHR.  Or play other levels first, and come back when you have some more heroes at your sides.
