### ISSUE TITLE
[Feature request] Create endless waves level

### ISSUE THREAD

**Issue by faan11** [ochadenas/cpudefense#36]
Hi,
I have been using this game for a while and i appreciate it. I had been able to finish the game (normal and turbo mode) even without the latest changes ( that reduces the difficulty of 22° and 23° levels). I have also obtained all the characters.

Did you ever consider a new mode after the turbo one? My idea is to create a new level with endless waves. Once the user loses, the user can share their records in a specific Github issue.

What do you think?

**Comment by ochadenas** [comment]
Yes, that's indeed an idea that I had. Or perhaps make a kind of auto-generated levels. But it'll take some time to implement this.

**Comment by faan11** [comment]
this is also a good idea. 

What about introduce heating over ADD, SHR and other instructions? They are processing bits and this should generate heat. After the temperature reaches a certain threshold, the computation slowdowns. The component will be removed or disabled if the temperature reaches another threshold. These thresholds should depend on the instructions lvl. The user can pay bits to add coolers or improve coolers that can be placed near the instructions to reduce the instruction's temperature.

This phenomenon should be noticeable when the difficulty raises.

**Comment by ochadenas** [comment]
I am currently working on an endless mode, but it is not easy to automatically generate interesting and appealing stage layouts.

And I have come back to your concept of "heat", I think it's really interesting, and it is a good means to counter-balance the effect of the CLK chip, which would get too powerful otherwise. In that way, it is not the normal chip operation that creates heat, but accelerating (or "overclocking" it). The mechanism now is this: Every time a chip's cooldown time is shortened by a CLK signal, the remaining wait time is converted into heat. Heat decreases slowly over time. If the global temperature reaches a given threshold, the CPU will take damage (i.e. the player loses a life).

And there will be a hero or two to decrease heating or improve cooling.

**Comment by Cwpute** [comment]
In version 1.27, there is an option in the settings that, if i understand it well, should "Keep the levels in infinite mode" (my interface is in french, not english) which i assume should let you play the level against infinte waves of ennemies. Right ?
But it doesn't work :( or i don't understand how it works.

**Comment by ochadenas** [comment]
I'm still working on it, it's not finished ...

**Comment by ochadenas** [comment]
Finally added the  endless series in 1.28. I'd be obliged if you could test this a bit and tell if it's ok, or too hard or too easy or too boring ...

**Comment by Cwpute** [comment]
will certainly do once it hits the Fdroid store !

Le 10 février 2024 09:10:30 GMT+01:00, ochadenas ***@***.***> a écrit :
