### ISSUE TITLE
Suggestion: Allow a faster fast forward. 

### ISSUE THREAD

**Issue by ThisIsPaulDaily** [ochadenas/cpudefense#40]
I recently had everything unlocked, but felt even on fast forward attackers were too slow. I reset everything and realized the pricing changed and don't have enough tokens to unlock everything again. Now I'm grinding away averaging a coin every 3-5 minutes. 

If I'm set up to crush a level by round 6, allow me to just faster fast forward through.

**Comment by ThisIsPaulDaily** [comment]
I feel I should add that I reset everything to not purchase the slow down attackers assist, which is helpful when starting, but troublesome when grinding for coins. 

I'm not looking to turn off the slow down abilities, but sort of like the clock fixes the timeout on parts, I want the game clock to go faster, so enemies still get hit the same amount and stuff, but just faster.

**Comment by Kutabu** [comment]
I support this feature request 👍

**Comment by ochadenas** [comment]
I have thought about this issue, but I have come to the conclusion that I rather won't do this. For two reasons.

First, technically. You can't just make the frame rate arbitrarily high. In fast-forward mode, the game already running as fast as possible. If you want to go still faster, you'll have to skip frames, which I fear will cause weird effects, such as attackers going through chips without being noticed.

And second, I don't like the idea of grinding for coins. It's true that the text in the game says, "you can repeat levels for coins if stuck", but that's not the same as running the level over and over again in order to purchase lots of heroes. In that case, it would be easier to make a button "give unlimited amount of coins".

Of course everyone is free to play the game the way they like, and there is no "correct" way to play it, but I feel that the interesting feature lies in developing strategies of how to place the chips and which heroes to hire.

I can assure you that it *is* possible to go through the whole game without grinding. I've done this many times for testing ...

**Comment by Kutabu** [comment]
If you don't want to support coin farms, that's perfectly fine. I didn't really need it either. I also wished for a faster fast-forward mode in normal game situations. 

But anyway: If you write that the frame rate is already reaching its maximum, then I'm unsure whether the frames are a suitable method for calculating the game elements. You have already introduced "ticks", so you could use them consistently. That would reduce the load on the graphics and save resources.
But I'm pretty sure that this thoughts are nothing new to you and rebuilding the whole mechanism would be a lot of work.

**Comment by ochadenas** [comment]
Added a "really fast forward" mode in version 1.27. Have a look at the "settings" screen.
