### ISSUE TITLE
Benoît Mandelbrot is not boosted by Sid Meir 

### ISSUE THREAD

**Issue by ThisIsPaulDaily** [ochadenas/cpudefense#44]
Title is the issue, also the text for Benoît Mandelbrot spells Graphical with the p and a transcribed "Grpahical".

**Comment by ochadenas** [comment]
Sure that you really mean Mandelbrot? Because Mandelbrot _is_ boosted, but Franke,  Zuse and Sid Meier himself are not.

Franke because that would made its delay time negative, Zuse because he is limited to level 3 (our computer has not that many LEDs for the lives...) and Meier himself because that would allow an infinite loop of upgrades.

Fixed the typo in the biography.

**Comment by ThisIsPaulDaily** [comment]
The text going from 8->9 says 4 bit/kill to 4bit/kill it may be a mistake.

**Comment by ochadenas** [comment]
The formula for Mandelbrot is level * 0.5, at least currently in v1.22. That means one additional coin/kill for every two levels (because there are no fractions of bits in the game).

This means that you will have to upgrade twice to see an effect. I also tried with 1.0 coin/kill per level, but that makes him completely overpowered. Mandelbrot is pretty strong anyway.
