### ISSUE TITLE
Flipped bits escape sub1

### ISSUE THREAD

**Issue by fschaupp** [ochadenas/cpudefense#50]
Im in level 1 und after tapping the 0 bits before the reach the sub1, some of them escape the sub1 and damage the CPU.
![Screenshot_2023-10-29-09-59-35-540_de chadenas cpudefense](https://github.com/ochadenas/cpudefense/assets/26521758/012edb32-9d93-41bc-b8d2-0308e2007819)

**Comment by ochadenas** [comment]
Well, you should *not* tap on 0's. Only on the 1's ... they'll become 0, and then the SUB chip can take them out.

In general, numbers where the first (left-most) bit is 1 become smaller through inverting. Those with 0 become bigger.

**Comment by fschaupp** [comment]
Well, why shouldn't I be able to make the 0 to a 1, where afterwards the SUB1 will eliminate it?

**Comment by ochadenas** [comment]
That's how the game is designed.

SUB 1 will subtract 1 from the number. It turns 1 into 0 and 0 into nothing. It's "nothing" that you want, because 0 still will cost a life.

Tapping inverts the number. It turns 1 into 0 and 0 into 1.

To get rid of a 1, you'll need either two SUB chips, or one that has been upgraded to SUB 2, or a really fast chip that can operate twice on the same attacker (that's for later in the game, when you have access to heroes). So better try to turn the 1s into 0s.

See also https://github.com/ochadenas/cpudefense/wiki/SUB

**Comment by fschaupp** [comment]
Well, then it's at least inconsistent, because sometimes it eliminates a 1 with just one block after touching the bottom border, when the 1 entered from the top.
