### ISSUE TITLE
Lost hero recruitment when updating to ver. 1.25

### ISSUE THREAD

**Issue by JosKabe** [ochadenas/cpudefense#60]
I updated from Ver. 1.24 to Ver. 1.25 and lost all my hero recruitment levels and therefore all the coins invested in them! That was a lot of work to get them back (i already had several heroes at level 10), is there any way to restore them?

**Comment by ochadenas** [comment]
Oh. That is indeed an ugly bug. Thanks a lot for the report. I have disabled the 1.25 version here in github in  order to fix that.

I fear that the information about the heroes is gone and cannot be recovered. I'll add a kind of correction routine, so that at least the coins gathered so far can be refunded.

**Comment by ochadenas** [comment]
Published version 1.26 which fixes the bug, and also tries to restitute the coins lost due to this bug.

**Comment by ochadenas** [comment]
Should be resolved now.
