### ISSUE TITLE
Review MEM chip usability

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#67]
I like the way the MEM chip works, but as it is now, they are quite uninteresting, and useless. I only ever used them in 3 levels after they were unlocked, before realizing they were basically useless.

Why canot they be upgraded in a game, once bought ? i'd love to make them faster by spending bits, at least they could compete in mid to high levels and act as failsafes before the core.

I think the way they work could even be changed entirely. Here are some ideas:
1. MEM chips would absorb attackers until their sum reaches a limit (that could be upgraded by spending bits) then it needs to cool down: at first the limit would be 1, then 11, then 111, then 1111 etc…
2. The way they work could be change on every upgrade, like the ACC chips do. I don't know how that would work tho.
3. MEM chips could be passive chips like CLK chips, that add some kind of "protection" layers to the core with each upgrade, that can reset over time. The explanation would be that it "stocks" the information before it reaches the core.
4. Another passive chip idea: they would highlight attackers below a certain value (that value would rise upon upgrading the chip) that would be marked for max-damage, or double-damage…

**Comment by ochadenas** [comment]
Funny that you should see it this way, because actually I thought that the MEM chips were quite _over_powered. For example, the layout ACC --> ACC --> ACC --> MEM is quite invincible, or would be, if it wasn't for the cryptocoins that go through this without damage. But you can easily win nearly every level with that, if you don't mind losing a life.

And in combination with CLK the MEMs become still more powerful. At the moment I'm experimenting with "endless" levels, where attackers get stronger and stronger. And there you have the effect that "buy lots of MEMs and have a really fast CLK" is by far the most effective strategy. It's because of MEM swallowing everything. I'm currently trying to limit the power of MEMs by introducing "heat". That wouldn't change much in the standard or even turbo levels, but would become a nuisance if there are really many attackers with a high frequency. But otherwise it would be too easy to win every game.

So don't worry, the MEM chip might not be of much use the time it is introduced, but it becomes stronger and stronger during the game.

If you want to have upgrades for MEM chips, I think the most natural way would be "can hold more than one value". So let's say a MEM 2 chip could swallow two attackers, and after its cooldown time one slot would be emtpied and could hold another one. This would help on the lower levels. On the higher levels one would still have problems with heat, which I think is ok. I'll think about how to implement this.

**Comment by Cwpute** [comment]
Oh interesting, never experimented with that setup having ACC chips-a-plenty and a MEM chip eating the rest in the end.

Both good ideas, higher levels of MEM being able to eat more values before cooldown, and having to deal with overheat.

**Comment by Cwpute** [comment]
> For example, the layout ACC --> ACC --> ACC --> MEM is quite invincible, or would be, if it wasn't for the cryptocoins that go through this without damage. But you can easily win nearly every level with that, if you don't mind losing a life.

Oh i think i get it.
To me, getting coins is not an option: it becomes the main objective. In the first levels, just getting through a level could be hard, but in the later, it wasn't really a matter of "if" but rather of "how", and specifically, with how much coins.
It became important pretty quickly in the game i think, to get back to previous levels and try to get that last coin, managing a perfect game.

So losing a life point might not be important if you just want to finish the game's missions; and MEM chips might seem overpowered to you. But if your objective is to get all the coins in all the levels, then the MEM chips are really bad.
Really depends! So they aren't so useless afterall, but to someone willing to outdo themselves, they quickly are!

**Comment by ochadenas** [comment]
Just consider it as a kind of challenge, so that the game doesn't become too easy ;)
