### ISSUE TITLE
Suggestions on negative chips

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#68]
I loved having to deal with negative chips, and i'd like to see them used in other situations.
Here are a couple of ideas. Feel free to use them or get inspiration from!

1. ~~Review the cost of removing negative chips: right now it costs the same to remove an ADD1 chip and to reduce the level of a SHL3 chip, but the impact of these two types of chips isn't the same at all.~~ **now being implemented!**
2. Let the player place down negative chips, giving him instantaneous bits in change for a possible problem later down the line. Alternatively these chips could cost nothing to place down, but slowly generating bits over time.
4. Generate chips that are direct counterparts to the CLK chip (accelerating attackers, or slowing down positive chips, or accelerating negative chips), the MEM chip (serving as attacker spawn points), and the ACC chip (cloning attackers).
5. ~~Have new recruits that lower the amount of negative chips at the start of a level, lower their level, and lower the price to remove them.~~ **now implemented !**

**Comment by Kutabu** [comment]
1. This is a reasonable argument. I see it as less necessary because the negative chips are more of a problem for me at the start of a level. As the negative chips are placed randomly, it's more a matter of luck how difficult a level is anyway. 
2. Very interesting idea! It would definitely change a lot of the gameplay and make new strategies possible. Unfortunately, it's just not feasible. If I interpret the code correctly, the reward is calculated once when the chips are generated via "attackerData.bits". An increase/decrease during a stage does not change this.
3. I find this difficult. In the context of a tower defence game, it might make sense. But the game is intended to reflect real calculation operations in the chips. There is no such thing as "clone a virus" at this computer level.
4. Possible :-)

**Comment by Cwpute** [comment]
> 1. This is a reasonable argument. I see it as less necessary because the negative chips are more of a problem for me at the start of a level. As the negative chips are placed randomly, it's more a matter of luck how difficult a level is anyway.

I agree that negative chips are mostly annoying when starting a level, if spawned in bad spots… but this can easily be mitigated by abusing the `restart level` feature to get better negative chip spawns. Hence my suggestion: it would give more wiggle room for thougtful action in the first moments of the game, whatever the spawn positions are, giving less incentive to just restart the game.

Maybe offer the option to replace a negative chip in another free slot for a small price in bits ? less so than removing a chip level of course, maybe half the price, or a third of it.

**Comment by ochadenas** [comment]
Very interesting ideas, thanks a lot. You are right that this could add a lot of possibilities for tactical game play. On the other hand, we should not make it _too_ complicated, because then the average player will have difficulties to cope with this. I mean, there are already up to 5 possibilities to choose from, I don't know where to place all the buttons for negative chips ...

> Review the cost of removing negative chips: right now it costs the same to remove an ADD1 chip and to reduce the level of a SHL3 chip, but the impact of these two types of chips isn't the same at all.

That should be feasible. But do you propose to make the more dangerous chips _less_ or _more expensive_ to remove? The thing is, if the player is faced with let's say SHL 3 instead of three times ADD 1, *and* it's more expensive to remove it, they will be even more likely to restart the level. So maybe the simple ADD chips should me _more_ expensive.

(Currently, the code works like this: It looks for a random slot among those that are not already occupied by a _positive_ chip (there are some levels with pre-defined chips). If the slot is empty, it adds a new negative chip. If there is already a negative chip, it raises its level. This operation is repeated _n_ times, where _n_ depends on the level.)

> Unfortunately, it's just not feasible. If I interpret the code correctly, the reward is calculated once when the chips are generated via "attackerData.bits"

Yes and no. It's true that the reward is calculated (to be precise: It's equal to the length of the binary number, cf. the [wiki page](https://github.com/ochadenas/cpudefense/wiki/Information)). But the calculation could be modified, and in fact is already for Mandelbrot's effect.

> I find this difficult. In the context of a tower defence game, it might make sense. But the game is intended to reflect real calculation operations in the chips.

Well, it *is* a game in the first place, not a computer simulation. It wouldn't give me really bad conscience. 

I have thought about a "splitter". That is a real-world computer component. It would turn an xABCD value into xAB00 and x00CD. Or, alternatively, to make things simpler, just into two equal copies of xABCD.

> Have new recruits that lower the amount of negative chips at the start of a level, lower their level, and lower the price to remove them.

Good idea.

**Comment by Cwpute** [comment]
> > [removal cost depends on chip power and type]
>
> That should be feasible. But do you propose to make the more dangerous chips less or more expensive to remove?
Dangerous chips should be more expensive.

Let's look at the the SUB1 chip: without upgrades, it costs 8b. The upgrade to SUB2 costs 12b more, so its value totals to 20 (the same you have to spend to remove its negative counterpart of a lower rank: ADD1). Now, SHR1 costs 16b to place down, and 24b to upgrade, which puts SHR2 to a total value of 40b. (the same value to remove two levels of any negative chip, SHL2 included).
If i'm in a situation where i have both an SHL and an ADD chip in my level, which should i chose to remove first ? right now the solution is easy: the SHL of course, especially in the beginning of a level when a single shift to the left can be catastrophic. ADD1 or even ADD2 can much more easily be dealt with, with a single tap on an attacker to reverse its value. Sometimes, it even gives you an incentive to keep that chip just to be able to heavily downgrade attackers with a single tap.
That choice would be much less automatic if the remove value depended on the value of its positive chip counterpart. I'd suggest trying between 120% and 200% its counterpart's value in bits. Now, should i put a positive chip right before or after the bad one to counter it, or should i remove that negative chip, by waiting and risking some attackers might pass ? and if sone do pass, do i panic-buy a positive chip or do i stand my ground and cross my fingers ?
I think it would make for much more interesting decisions.

Now of course that would make the negative chips quite harder to deal with. But the fact they already take an available space is already bad enough. So having less of them in harder levels might be for the bettes

**Comment by Cwpute** [comment]
Which gives me an additional idea for negative chips:
5. A chip that does not do anything, but just sits there and needs to be removed to recover that space.

**Comment by Cwpute** [comment]
> The thing is, if the player is faced with let's say SHL 3 instead of three times ADD 1, and it's more expensive to remove it, they will be even more likely to restart the level
Forgot to add: yes! which calls for a new way to weight negative chips. Instead of having a set number of them in each designated level, the computer gets a "budget" to buy these negative chips with. So for example fwr level 23, the coméuter would have a negative chip "budget" of 30b: which would let him buy, idk… an ADD1 and an ADD2 chip, or an ADD1 and a SHL1 chip (that would all depend on the cost of removing them that would be changed according to my suggestion)

**Comment by Cwpute** [comment]
> I have thought about a "splitter". That is a real-world computer component. It would turn an xABCD value into xAB00 and x00CD. Or, alternatively, to make things simpler, just into two equal copies of xABCD.

This is perfect! Not an exact equivalent to the ACC, but it's alread super interesting that this exists in the real world :)

**Comment by Cwpute** [comment]
> > 2. [let the player place down negatives for a reward]
>
> […] I mean, there are already up to 5 possibilities to choose from, I don't know where to place all the buttons for negative chips ...

I agree it shouldn't be much bigger than that. But see, right unedr the CLK chip, you put down a buton that swaps between positive chips and their counterparts 👀
Heck, you can even just give that space to a "default" negative chip, which is then randomly chosen between the ones available. The reward would always be the same, but the negative side could be reaaally bad. Hoping for an ADD1 ? you get a SHL1, too bad !

**Comment by ochadenas** [comment]
I have had not much time recently and have not gone any further with all these suggestions.

However, at least the "chip that does not do anything, but just sits there" now exists (version 1.27).

**Comment by CrsiX** [comment]
I would suggest a `NOT` chip which performs the one's complement (each 1 becomes a 0, each 0 becomes a 1). This chip performs exactly the same operation that the player could do by tapping on a number. It is a negative chip, because usually a player will try to get the number to zero (e.g. by `AND` or `SHL`), but this would increase a zero to its max value again. It can obviously not be upgraded (like the `NOP` chip).

Another suggestion would be to reverse a value, similar to the `BSWAP` operation ([Intel x86 manual for this instruction](https://www.felixcloutier.com/x86/bswap)). In contrast to the real-world instruction, I would reverse bit-wise and not byte-wise, though, and I would therefore call it `REV` for reverse. It depends whether you want to have an instruction set that is possibly close to real-world instruction set or not. If so, then either use `BSWAP` as it is the operation name and its operation is byte-wise, or let it out entirely. If included, this chip could not be upgraded (and it could handle any input size, not just 32bit or 64bit inputs). It is a negative chip, since it complicates the processes a bit. If it was used at the beginning of a stage, it may have no big influence, though.  
Examples:
- 0x00 would not be affected, similar to 0xFF
- 0x0001 would become a 0x8000 (`REV`) or a 0x0100 (`BSWAP`)
- 0x0101 would become a 0x8080 (`REV`) or would stay 0x0101 (`BSWAP`)
- 0x1337 would become a 0xecc8 (`REV`) or a 0x3713 (`BSWAP`)

**Comment by ochadenas** [comment]
I have thought again about the removal of chips. The main problem (as I see it) is that removing is just a question of money. So basically each level of Kilby equals 20 bits of info. It's just too cheap to remove all of them.

This would only partially be mended by making SHL more expensive than ADD. Besides, during the first waves, ADD can be more annoying than SHL (because if you shift 0x00 you still end up with 0x00. And 0x01 only becomes 0x02.)

What do you think of these ideas?
- Whenever placing an ADD 1 chip, automatically upgrade it to ADD 2. And NOP to NOP 3.
- Making some chips immobile, so that they cannot be removed. (But how to determine which ones?)
- Make the price dependent on the number of chips already removed. Which would mean that you could only remove some of the unwanted chips before removal becomes too expensive.

**Comment by Kutabu** [comment]
- Placing ADD2 and NOP3 is a possibility to make it more challenging, but I prefer the third idea. 
- In endless random generated levels, immobile chips may sit on a position, where they block an important spot. In pre-defined level, they add an interesting element! I would consider to take it into the gameplay for these levels.
- Increasing the price depended on the number already removed, seems so me the best idea. At the beginning on an level, negative chips may be annoying, but after some rounds, the negative chips are no problem at all. Increasing the cost may change this.

**Comment by CrsiX** [comment]
> Make the price dependent on the number of chips already removed.

I upvote the third idea, with the second idea only for predefined levels, and clearly visually distinguishable from removable chips (e.g. greyed out or so)

**Comment by Cwpute** [comment]
> […] So basically each level of Kilby equals 20 bits of info. It's just too cheap to remove all of them.

Well then maybe, instead of strictly removing one negative chip per recruit level, Kilby upgrades could work like Mandelbrot's : you'de have toqinvest in several levels of "blank upgrades" before being benefiting from a second or third negative chip removed.
My prefered suggestion would be to have Kilby decrease the price for negative chip removal by a percentage.

**Comment by Cwpute** [comment]
> we could have another hero for reducing the price.

Bad idea :/ you'd end up with one hero that straight up removes a level of negative chip (20bits economized, and no bother from having the chip set in the first place, and a second hero that just reduces the price for removal… whuch both require the same amount of cryptocoins to upgrade.

Le 8 mars 2024 19:11:45 GMT+01:00, ochadenas ***@***.***> a écrit :

**Comment by ochadenas** [comment]
Yes, but in combination with increasing prices, the second one could have its value.

**Comment by ochadenas** [comment]
Some more thoughts on this ...

Seems that getting a good balance for these negative chips is quite hard, we'll need probably some more iterations.

And I must admit that I never thought that one would play up to level 80 or 90 or more. I never tested beyond level 20 ;) As of 1.30, in higher levels there will be a *really*  **HUGE** number of negative chips, making the levels unplayable.

In 1.31, I'll try the following:

There will be two more kinds of chips, as @Cwpute suggested somewhere up in this thread: DUP that duplicates (clones) an attacker, and SPLT that splits up a number, e.g. x4F in x40 and x0F. This will raise the number of negative chip types to 5; I consider that this is sufficient, and that more types will not add much to game play.

Each of these types get a "difficulty", or "hardness" assigned. For instance,
  * NOP -> 1.0
  * ADD -> 2.0
  * SHL -> 2.5
  * SPLT -> 3
  * DUP -> 3,5
Each stage has a target difficulty, depending on its number. The sum of the unwanted chip values then should match approximately this target. 

The number of chips must however somehow be capped.

I think that a second hero acting on negative chips would still be a good idea, just to have two of them. Perhaps keep this for 1.32.

**Comment by Kutabu** [comment]
The two new chips sound good :-)

I would like to suggest that the DUP or SPLT attackers are either released with a time delay or have a significantly different speed. In my opinion, dealing with two attackers at the same time is the most difficult part of the game.
Talking about this... a negativ **SYNC-Chip** is also possible, where an attacker is temporarily saved and released synchronised with another attacker.

**Suggestion for the SPLT chip**: These can either halve the numerical value (decimal) or simply split bit/byte.  
24 = 0001 1000
- 0001 and 1000 **or** 
- 1100 and 1100

**Comment by Kutabu** [comment]
@ochadenas If the negative chip system has to be changed, then one possibility would be to use two factors:

1. there is a difficulty-scoring, as you suggested. I'm not sure whether it has to be "sum = level". I think it would have to be cut for higher levels or asymthotically approach a limit value.
2. there is a limit to the maximum number of chip positions occupied at the level. This could be a percentage value.

As you mentioned in https://github.com/ochadenas/cpudefense/issues/68#issuecomment-1988406871, it would be a good option to use two heroes that affect the negative chips. They could have a percentage effect on each of the two factors. In any case, this would be better than the current "conversion" of one level at Kilby = -20 bit.

**Comment by ochadenas** [comment]
The "reduction by percentage" hero now exists (Margaret Hamilton). She gives a general discount of 8% per hero level.

The idea of limiting the occupied slots to a certain percentage is good, will think of how to implement this.
