### ISSUE TITLE
Exploit to refund more that was invested

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#71]
A Sid Meier exploit similar to #62 can be performed Jack Tramiel, that allows you to get a refund that surpasses the initial value at which you bought a chip (up to 140% of its initial value).

This means you can repeatedly buy and sell a chip for a free return in bits, without actualy playing the game !
Profit 🤑

**Comment by ochadenas** [comment]
Yes, true. But unlike the Bruce Schneier exploit I was aware of that ;) 

I think it's not so much a problem. If you can make some cash that way, why not ... but it's rather tedious, and you can't gain very much this way. Economically it's much more advantageous to level up Benoît Mandelbrot. Or even Hollerith.

**Comment by ochadenas** [comment]
Have had a second thought about this. You are right, this _is_ a problem. Or it has become one in the latest version, because it is now possible to buy and sell chips in PAUSED mode, without un-pausing the game. That will actually allow to gain an arbitrary amout of cash at the start of each level.

Better limit Tramiel to 100% efficiency.

**Comment by ochadenas** [comment]
in version 1.27, Tramiel is limited to level 6. (This still gives a refund of 110%.)
