### ISSUE TITLE
Don't use system fonts

### ISSUE THREAD

**Issue by BloodRaven0** [ochadenas/cpudefense#75]
I have a custom font selected that makes the zero a perfect circle, which takes up a lot of space. When long numbers start coming, they overlap a lot and are impossible to see or click.

Besides, using a custom font will make the game look better. Get some font with super narrow zeroes and ones for the enemies and some techy font for the menus. The text bodies (the heroes descriptions) should still use some easily-readable font though.

Experiment a bit :)

**Comment by klaviartur** [comment]
For me, chip names don't fit into the slot when upgraded, e.g. SHR 10 looks the same as SHR 12.

**Comment by ochadenas** [comment]
Changed the font for chips and codes to Ubuntu Mono. That's a rather narrow font; however, it does not exist in a condensed version, so on my device it takes up slightly more space than before, but it still fits. Have a look at it on your phone.

Also addressed @klaviartur 's problem: The chips with strength 10 and above are now written without space, e.g. SHR10 instead of SHR 10.
