### ISSUE TITLE
Two attackers on the same spot = untouchable

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#76]
I had a game on which an attacker and cryptocoin seemingly spawned exactly on the same pixel (could be an attacker from an ACC chip) which prevented any of them two to trigger chips and thus be attacked.

This should probably not happen! Perhaps gently slow one down or push one of them one pixel away as to not be on the exact same spot.

**Comment by ochadenas** [comment]
The atackers already have a small random displacement added to their position, in order to avoid them being in the same place. But of course, as attacker frequency goes up, then there is a certain probability that this happens.

They could be given a small random difference in speed, but that would look "untidy", I think. But perhaps after leaving the ACC chip this would be possible.

Even so, I would expect one of the two attackers to be "hit" by chips. The other one indeed would go through unnoticed.

**Comment by ochadenas** [comment]
attackers now have a small random change in speed when leaving the ACC chip. Let's see whether this solves the problem.

**Comment by Cwpute** [comment]
As you said, this will look a bit untidy, it will have to do for now.
You could have the chip check the spot at which it should spawn the operation-resulting attacker, and see if there already is an attacker there, but i guess that would be a bit more work.

I think ultimately you may have to implement a hard limit to the shortest distance possible between two attackers, to prevent situations in which you can't tap on them (and reswlve this issue as well).

Le 18 janvier 2024 18:24:59 GMT+01:00, ochadenas ***@***.***> a écrit :
