### ISSUE TITLE
Separate upgrade points for Endless mode

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#97]
I feel the recent Endless mode suffers from inheriting the upgrades and cryptocoins from the previous Normal and Turbo modes.

You enter the first Endless levels with a huge amount of upgrade points that renders them trivial and uninteresting. But as the difficulty (slowly) increases, it requires you farm many more cryptocoins for increasingly costly upgrades that don't even impact that much.
This gives the Endless mode a rather short "sweet spot" where your own level of upgrades and the generated level's difficulty match so as to provide you with a good challenge, and the rest being either too easy and uninteresting, or frustratingly hard.

For this reason i'd suggest having Endless start with your cryptocoins and recruit upgrades back to zero. The cryptocoins and upgrades you'd get through Endless would only be usable there.
Maybe even have a different cryptocoin colour so as to be clear the upgrades aren't shared with Normal and Turbo.
This would allow for a broader difficulty range and level variety (#95) to be experienced in this mode !

**Comment by The-JMFB** [comment]
Alternatively, maybe a completely new/different set of chips or upgrades are in order. Prior to the release of endless mode, I would play through all 56 levels sequentially and not advance to the next level until I completed the current level perfectly (no lives lost). Once level 28 Turbo was completed, I reset and start over. This game has become something of a meditation for me. I play in the mornings while sitting on my patio and having my coffee, during my work breaks, in waiting rooms etc.

Endless mode was appealing, at first, for the sake of simply focusing on the level strategy rather than the the"big picture" upgrade strategy as the primary focus. The first few levels, of course, were fairly simple with my current upgrades, but it was no different than starting Turbo mode with the upgrades accumulated from normal mode. As expected, the difficulty soon matched my upgrades, then rapidly exceeded them. I slowly balanced my upgrades with the difficulty - well, maybe not balanced, but closed the gap. 

However, it was not long until all upgrades were purchased and the difficulty continued to accelerate. Once you get into endless levels ~50+ you can't even bother trying the smaller maps. There is no strategy that can possibly survive beyond wave ~40 on a small map. If you cannot place at least 4-5 chips between the entry and the CPU, you are going to lose. The attackers are so powerful and so numerous that you can watch some of them enter the map so close to another attacker that they glide over chips, untouched. Sometimes all the way to the CPU without a single chip affecting them. 

Then there is the clock chip. Obviously, it's absolutely mandatory in every level after a fairly early endless level. Overheating soon becomes a major problem simply because of the number of attackers, and irrespective of the number or level of chips in the higher levels. For endless mode, we really need a significant nerf to the temperature or, better yet, perhaps a CPU cooler upgrade path for endless mode? I'm at level 67 and have had no upgrades left to purchase for quite some time now, so there is definitely room for more upgrades in endless.

Also, to help with the volume, speed and frequency of attackers in the higher levels, perhaps some additional upgrades for the mem and acc chips to help "thin the herd" and make these levels more strategically viable? At this point, I feel like it's really just luck to survive a level anymore. As soon as the level loads, I reset it and load again unless the map is large enough to have any chance of success. This usually takes 5-10 resets per level. Even then, survival is basically luck. Usually by the skin of my teeth. It's difficult to have endless increase in attacker frequency and strength with no way to improve your defense strength. The attackers have become less and less stoppable no matter how many chips or what level those chips are. Additionally, the cost of chip level increases is so high that the higher levels are becoming unbalanced after ~10-15 waves because the attackers are already so much more powerful than your chips, so your chip level increases are always well behind the attackers strength increases.

As another possible solution, perhaps the current upgrades continue as they currently exist but you could add more upgrades that are purchased for the current level to boost those original upgrades. Perhaps introducing a new currency to earn during the Endless level and spent only in that level from the pause menu or maybe between waves? Maybe instead of more endless levels, it becomes simply a single endless level and each "level" is instead the next wave? After each wave, you could use your accumulated currency to purchase chip boosts, additional chip slots for the map, 
etc. and make it more of a "choose your own adventure" type of endless mode.

I recognize and appreciate the difficulty of offering an "endless" mode that is satisfying, balanced and engaging - please don't take these criticisms as negative commentary because they are not intended as such. This game is brilliantly simple, yet rewarding and challenging enough to enjoy it over and over again. I will gladly continue to reset and start over - with or without playing endless mode.

**Comment by Cwpute** [comment]
Thanks for the detailed feedback ! it pretty much mirrors my own, and i share most of your gripes with the difficulty.

> you could add more upgrades that are purchased for the current level to boost those original upgrades.

Stronger updates for current recruits is quite an easy thing to do i believe: unlock the limited number of extra upgrades (Sid Meier) for every recruit currently limited to… 3 i think ?, and procedurally generate new upgrades past that point that increment recruit benefits. I believe each upgrade cost and benefit is manually set as of now, so that would still be some work, but still quite feasable.
New upgrades could be envisioned, yes: you evoked possible MEM and ACC chip upgrades, some that would improve their speed and attack range would be pretty straightforward to implement.

> Alternatively, maybe a completely new/different set of chips or upgrades are in order.

… but that! would be quite another can of worms, and a lot of work! lore-wise and gameplay-mechanics-wise. If you do come up with fitting new chip ideas, make sure to suggest them in a new issue because i bet they'd also be intersting for regular levels :p

> Perhaps introducing a new currency to earn during the Endless level and spent only in that level 

Indeed that's pretty much the idea i suggested in the first message of this suggestion, glad you came up with a similar conclusion :)

Le 25 février 2024 18:41:09 GMT+01:00, The-JMFB ***@***.***> a écrit :

**Comment by ochadenas** [comment]
You have me convinced ;) Will try  to have a separate update path for the "endless" series, but this needs some work, and will have to wait until 1.31 or 1.32.

But at least there is a new hero (Claude Chappe) in 1.30 who reduces heat generation.

**Comment by VA1DER** [comment]
I disagree with the hero reset.  After the standard levels, I find (only on level 11 of endless) that some of them were already far too difficult.  With many levels the number of possible starting points and path diversions makes only with multiple tries and luck where some paths aren't chosen until I can get enough info to populate them.  If my heroes were reset, I'd be unable to progress at all. As it is, I am having to employ heavy micromanaging, very fast footwork, and can spend more time paused than playing.

The issue I see with "endless mode" the way it's implemented now is that it is at odds with the tower defense format.  Tower defenses are supposed to be primarily strategic, and the way endless mode is now makes the levels more difficult by making them increasingly tactical.  This means that as players move up you are pushing them more towards a different kind of game than they started playing.  

When I saw endless mode, I worked to unlock it because I thought it was finally a mode where the **attackers** were endless, not the levels.  I am disappointed when I reach the end with many levels because I love my defense designs and would love to test them against really tough waves and see how far I can get before the design cracks, then go back and tweak it.

Randomly generated levels have their place, and I would keep that paradigm, but I would put them in as something the player activates and controls.  Give the player more control over them and have it as a way for the player to generate challenging courses when the current ones are boring.  But I would wholeheartedly recommend that "endless" mode be switched to endless attackers.  Give the player a way to set the initial difficulty and see how far they can get before their defense crumbles.  Perhaps you can refuse to send coins on a level replay until: 1) the player reaches a wave past the highest previously achieved , or 2) the player runs that level with a higher initial difficulty (which should be rewarded).

**Comment by Cwpute** [comment]
> I disagree with the hero reset. After the standard levels, I find (only on level 11 of endless) that some of them were already far too difficult.

I dudn't have the opportunity to play 1.30, but i believe the difficulty of early levels will be less difficult in order to adapt to this idea ? if not, it definitely should.

> Tower defenses are supposed to be primarily *strategic*, and the way endless mode is now makes the levels more difficult by making them increasingly *tactical*.

I'm not sure i understand the difference you make between strategic and tactical, could you elaborate ?

I am on bward with you idea for your own vision of Endless ! it feels like we were all expecting this kind of endless levels to come up, and instead we got procedurally generuted levels haha. Which is great ! but very different.
We've requested such endless levels with increasingly difficult wave by the past, but neverv formally, maybe it's time to open a suggestion-issue for it !…

Le 6 mars 2024 03:07:27 GMT+01:00, Kurt Fitzner ***@***.***> a écrit :

**Comment by VA1DER** [comment]
> I'm not sure i understand the difference you make between strategic and tactical, could you elaborate ?

Strategic vs tactical is like playing Risk vs playing Call of Duty.  Tower defense games aren't intended to be click speed.  You are setting up a defense strategy and letting your defenses engage the hostiles.  You aren't in there at the tactical level shooting the bad guys one by one yourself.  The way this one is structured with random levels requires you to micromanage to such an extent at later levels that it changes the whole feel and genre of the game.

**Comment by Cwpute** [comment]
Ok i understand better.
It is very true that the game feel changes a lot, and quite quickly too. Once you hit around level 20 Normal, you never face new serious threats that drastically change your strategy, and by the start of Endless, you're micromanaging a lot already.

I don't think this game feel isn't compatible with tower defense; in fact, the mix of strategy and tactics is what hooked me in at first, personally: planning out your chip placement, but having to adapt as the level unravels. The balance between the two is very broken in Endless levels, and needs to be adressed at some point, yes, but i still think that when the two are needed at varying and balanced degrees, the game feels better than ever :)

Le 8 mars 2024 00:57:42 GMT+01:00, Kurt Fitzner ***@***.***> a écrit :

**Comment by Cwpute** [comment]
Maybe this difference between strategy and tactics is what i tried to describe in my topic, regarding a possible distinction between skirmishes and a campaign 🤔

Le 8 mars 2024 00:57:42 GMT+01:00, Kurt Fitzner ***@***.***> a écrit :

**Comment by The-JMFB** [comment]
> > I'm not sure i understand the difference you make between strategic and tactical, could you elaborate ?
> 
> Strategic vs tactical is like playing Risk vs playing Call of Duty. Tower defense games aren't intended to be click speed. You are setting up a defense strategy and letting your defenses engage the hostiles. You aren't in there at the tactical level shooting the bad guys one by one yourself. The way this one is structured with random levels requires you to micromanage to such an extent at later levels that it changes the whole feel and genre of the game.

![Screenshot_20240309_095127](https://github.com/ochadenas/cpudefense/assets/39312465/fad5f5e7-ade6-40a5-8609-28705386a18f)

I'll agree with you that the style of play is a little different, though not entirely. I believe that screenshot is from level 87. Level 88 was much smaller and I almost didn't play that map because I felt like it wasn't large enough to sustain 90 waves. To my immense surprise, I was wrong and actually completed that level with 4 lives remaining. I have a dragon hoard of unspent crypto coins. At these levels, the first dozen or so waves are definitely more "tactical" and require significant dynamic adjustments and micromanagement. Once I get through that window, though, it's back to the coffee sipping and slower paced  level increases.

Your defense strategy has to adjust for these levels, and you don't have the luxury of laying out your long term defense from the start. You need a short term, "tactical", front line defense while you build build your long term defense behind it. Personally, I enjoy the challenge. Believe me when I say that playing that many waves can get very tedious and boring if adjustments are not required.

The most frustrating aspects, for me, are the number of level resets I need to get a viable map and the absolutely maddening instances of so many FAST attackers flooding the map that I can watch several of them glide over many chips without being modified a single time. The sub chips at max level are also infuriatingly ineffective. The clock chip doesn't consistently deliver the results one would expect either. It's frustrating to see a severely weakend attacker glide over my final sub chip and barely take damage with a clock chip at level 10+. The manual reset of the mem chips has increased the pain because I generally use them as my final safety net (to catch those dirty cheaters that make it through my defenses unscathed) and when the preceding chips fail to be effective against a large swarm, that's when I tend to lose the most lives.

All of that said.... I'm still playing :)

I have reset twice more since endless mode was added, and I'll likely reset again in the next day or two just so I can play some shorter levels again for a day or two.

**Comment by ochadenas** [comment]
Ok, many of the suggestions here have been implemented now. There is a separate set of coins and heroes, MEMs can be upgraded, and there is a new chip type to slow down attackers (even if I think that these resistors still need a lot of balancing before being really useful).

Therefor I'll close this issue, to clean up the issue list a little. Feel free to continue discussing your strategies and experiences on the discussion page!
