### ISSUE TITLE
Consistency of attacker lane appearance

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#98]
During my time with Endless, i came across a lot of cases in which the difference in lane size (a lane being 1, 2 or 3 copper lines thick) made the level harder to understand.

Previously it's been thorized that lane size implied less or more chance for an attacker to chose it in a branching path (@juleskers in https://github.com/ochadenas/cpudefense/issues/46#issuecomment-1785969061 ):
> Speaking of PCB-traces: is there any significance to their "width"? I have seen 1-wide, 2-wide and 4-wide, but don't know if this actually means anything.

… when it doesn't.
Maybe it's time copper line numbers get some useful meaning, at least for randomly generated levels, so it doesn't get in the way of understanding the level.

Below an example of inconsistent copper line numbers that just add to the cluter of the level.
![line of mem](https://github.com/ochadenas/cpudefense/assets/80604512/17aed447-6f3f-46e3-beda-58c9f50286da)

**Comment by vertigo220** [comment]
Somewhat related, one of the frustrations I've had with this otherwise excellent game so far is having them seem to randomly choose paths, which can result in them sneaking through unexpectedly. The place this was the most annoying, causing me to have to restart the level numerous times, was level 8 (the same one in the linked issue). Multiple times, an attacker would go straight through the second block instead of going up or down to loop around, and this would result in an impossible situation, as it would happen before there was enough time to get enough bits to place a second chip.

**Comment by ochadenas** [comment]
Starting from version 1.29, the number of lines have an actual meaning (only in endless levels. In normal and turbo series the connectors are still purely decorative.)
